-- MySQL Script generated by MySQL Workbench
-- Fri Sep 20 15:54:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecommerceidea
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerceidea
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerceidea` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema bsm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bsm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bsm` DEFAULT CHARACTER SET latin1 ;
USE `ecommerceidea` ;

-- -----------------------------------------------------
-- Table `ecommerceidea`.`family`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerceidea`.`family` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`family` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `code` VARCHAR(3) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ecommerceidea`.`familysize`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerceidea`.`familysize` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`familysize` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `family_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sizes_family1_idx` (`family_id` ASC),
  CONSTRAINT `fk_sizes_family1`
    FOREIGN KEY (`family_id`)
    REFERENCES `ecommerceidea`.`family` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerceidea`.`lens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerceidea`.`lens` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`lens` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `angle` INT(11) NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `price` INT(11) NOT NULL,
  `familysize_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lens_familysize1_idx` (`familysize_id` ASC),
  CONSTRAINT `fk_lens_familysize1`
    FOREIGN KEY (`familysize_id`)
    REFERENCES `ecommerceidea`.`familysize` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ecommerceidea`.`driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerceidea`.`driver` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`driver` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `familysize_id` INT(11) NOT NULL,
  `dim` BINARY(4) NOT NULL,
  `brand` VARCHAR(20) NULL,
  `current` INT(10) NOT NULL,
  `voltage` INT(10) NOT NULL,
  `image` VARCHAR(255) NULL,
  `price` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_driver_familysize1_idx` (`familysize_id` ASC),
  CONSTRAINT `fk_driver_familysize1`
    FOREIGN KEY (`familysize_id`)
    REFERENCES `ecommerceidea`.`familysize` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ecommerceidea`.`frame`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerceidea`.`frame` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`frame` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `image` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `price` INT(11) NOT NULL,
  `familysize_id` INT(11) NOT NULL,
  `image2` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_frame_familysize1_idx` (`familysize_id` ASC),
  CONSTRAINT `fk_frame_familysize1`
    FOREIGN KEY (`familysize_id`)
    REFERENCES `ecommerceidea`.`familysize` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ecommerceidea`.`LED`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerceidea`.`LED` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`LED` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `power` INT(11) NOT NULL,
  `size` VARCHAR(20) NOT NULL,
  `color_t` INT(11) NOT NULL,
  `image` VARCHAR(255) NULL,
  `price` INT(11) NOT NULL,
  `familysize_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LED_familysize1_idx` (`familysize_id` ASC),
  CONSTRAINT `fk_LED_familysize1`
    FOREIGN KEY (`familysize_id`)
    REFERENCES `ecommerceidea`.`familysize` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ecommerceidea`.`colors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerceidea`.`colors` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`colors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `color` VARCHAR(7) NOT NULL,
  `price` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerceidea`.`colors_has_familysize`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerceidea`.`colors_has_familysize` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`colors_has_familysize` (
  `colors_id` INT NOT NULL,
  `familysize_id` INT(11) NOT NULL,
  PRIMARY KEY (`colors_id`, `familysize_id`),
  INDEX `fk_colors_has_familysize_familysize1_idx` (`familysize_id` ASC),
  INDEX `fk_colors_has_familysize_colors1_idx` (`colors_id` ASC),
  CONSTRAINT `fk_colors_has_familysize_colors1`
    FOREIGN KEY (`colors_id`)
    REFERENCES `ecommerceidea`.`colors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_colors_has_familysize_familysize1`
    FOREIGN KEY (`familysize_id`)
    REFERENCES `ecommerceidea`.`familysize` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `bsm` ;

-- -----------------------------------------------------
-- Table `bsm`.`optiongroups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bsm`.`optiongroups` ;

CREATE TABLE IF NOT EXISTS `bsm`.`optiongroups` (
  `OptionGroupID` INT(11) NOT NULL AUTO_INCREMENT,
  `OptionGroupName` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`OptionGroupID`))
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_german2_ci;


-- -----------------------------------------------------
-- Table `bsm`.`options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bsm`.`options` ;

CREATE TABLE IF NOT EXISTS `bsm`.`options` (
  `OptionID` INT(11) NOT NULL AUTO_INCREMENT,
  `OptionGroupID` INT(11) NULL DEFAULT NULL,
  `OptionName` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`OptionID`))
ENGINE = MyISAM
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_german2_ci;


-- -----------------------------------------------------
-- Table `bsm`.`orderdetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bsm`.`orderdetails` ;

CREATE TABLE IF NOT EXISTS `bsm`.`orderdetails` (
  `DetailID` INT(11) NOT NULL AUTO_INCREMENT,
  `DetailOrderID` INT(11) NOT NULL,
  `DetailProductID` INT(11) NOT NULL,
  `DetailName` VARCHAR(250) NOT NULL,
  `DetailPrice` FLOAT NOT NULL,
  `DetailSKU` VARCHAR(50) NOT NULL,
  `DetailQuantity` INT(11) NOT NULL,
  PRIMARY KEY (`DetailID`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_german2_ci;


-- -----------------------------------------------------
-- Table `bsm`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bsm`.`orders` ;

CREATE TABLE IF NOT EXISTS `bsm`.`orders` (
  `OrderID` INT(11) NOT NULL AUTO_INCREMENT,
  `OrderUserID` INT(11) NOT NULL,
  `OrderAmount` FLOAT NOT NULL,
  `OrderShipName` VARCHAR(100) NOT NULL,
  `OrderShipAddress` VARCHAR(100) NOT NULL,
  `OrderShipAddress2` VARCHAR(100) NOT NULL,
  `OrderCity` VARCHAR(50) NOT NULL,
  `OrderState` VARCHAR(50) NOT NULL,
  `OrderZip` VARCHAR(20) NOT NULL,
  `OrderCountry` VARCHAR(50) NOT NULL,
  `OrderPhone` VARCHAR(20) NOT NULL,
  `OrderFax` VARCHAR(20) NOT NULL,
  `OrderShipping` FLOAT NOT NULL,
  `OrderTax` FLOAT NOT NULL,
  `OrderEmail` VARCHAR(100) NOT NULL,
  `OrderDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `OrderShipped` TINYINT(1) NOT NULL DEFAULT 0,
  `OrderTrackingNumber` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`OrderID`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_german2_ci;


-- -----------------------------------------------------
-- Table `bsm`.`productcategories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bsm`.`productcategories` ;

CREATE TABLE IF NOT EXISTS `bsm`.`productcategories` (
  `CategoryID` INT(11) NOT NULL AUTO_INCREMENT,
  `CategoryName` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`CategoryID`))
ENGINE = MyISAM
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_german2_ci;


-- -----------------------------------------------------
-- Table `bsm`.`productoptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bsm`.`productoptions` ;

CREATE TABLE IF NOT EXISTS `bsm`.`productoptions` (
  `ProductOptionID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ProductID` INT(10) UNSIGNED NOT NULL,
  `OptionID` INT(10) UNSIGNED NOT NULL,
  `OptionPriceIncrement` DOUBLE NULL DEFAULT NULL,
  `OptionGroupID` INT(11) NOT NULL,
  PRIMARY KEY (`ProductOptionID`))
ENGINE = MyISAM
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_german2_ci;


-- -----------------------------------------------------
-- Table `bsm`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bsm`.`products` ;

CREATE TABLE IF NOT EXISTS `bsm`.`products` (
  `ProductID` INT(12) NOT NULL AUTO_INCREMENT,
  `ProductSKU` VARCHAR(50) NOT NULL,
  `ProductName` VARCHAR(100) NOT NULL,
  `ProductPrice` FLOAT NOT NULL,
  `ProductWeight` FLOAT NOT NULL,
  `ProductCartDesc` VARCHAR(250) NOT NULL,
  `ProductShortDesc` VARCHAR(1000) NOT NULL,
  `ProductLongDesc` TEXT NOT NULL,
  `ProductThumb` VARCHAR(100) NOT NULL,
  `ProductImage` VARCHAR(100) NOT NULL,
  `ProductCategoryID` INT(11) NULL DEFAULT NULL,
  `ProductUpdateDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `ProductStock` FLOAT NULL DEFAULT NULL,
  `ProductLive` TINYINT(1) NULL DEFAULT 0,
  `ProductUnlimited` TINYINT(1) NULL DEFAULT 1,
  `ProductLocation` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`ProductID`))
ENGINE = MyISAM
AUTO_INCREMENT = 991
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_german2_ci;


-- -----------------------------------------------------
-- Table `bsm`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bsm`.`users` ;

CREATE TABLE IF NOT EXISTS `bsm`.`users` (
  `UserID` INT(11) NOT NULL AUTO_INCREMENT,
  `UserEmail` VARCHAR(500) NULL DEFAULT NULL,
  `UserPassword` VARCHAR(500) NULL DEFAULT NULL,
  `UserFirstName` VARCHAR(50) NULL DEFAULT NULL,
  `UserLastName` VARCHAR(50) NULL DEFAULT NULL,
  `UserCity` VARCHAR(90) NULL DEFAULT NULL,
  `UserState` VARCHAR(20) NULL DEFAULT NULL,
  `UserZip` VARCHAR(12) NULL DEFAULT NULL,
  `UserEmailVerified` TINYINT(1) NULL DEFAULT 0,
  `UserRegistrationDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `UserVerificationCode` VARCHAR(20) NULL DEFAULT NULL,
  `UserIP` VARCHAR(50) NULL DEFAULT NULL,
  `UserPhone` VARCHAR(20) NULL DEFAULT NULL,
  `UserFax` VARCHAR(20) NULL DEFAULT NULL,
  `UserCountry` VARCHAR(20) NULL DEFAULT NULL,
  `UserAddress` VARCHAR(100) NULL DEFAULT NULL,
  `UserAddress2` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_german2_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
