-- MySQL Script generated by MySQL Workbench
-- Fri Sep 20 15:54:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecommerceidea
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerceidea
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecommerceidea`;
CREATE SCHEMA IF NOT EXISTS `ecommerceidea` DEFAULT CHARACTER SET latin1 ;
USE `ecommerceidea` ;

-- -----------------------------------------------------
-- Table `ecommerceidea`.`family`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerceidea`.`family` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`family` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `code` VARCHAR(3) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
     `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ecommerceidea`.`lens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerceidea`.`lens` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`lens` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `angle` INT(11) NOT NULL,
  `image` VARCHAR(255),
  `price` decimal(10,2) NOT NULL,
  `family_id` INT(11) NOT NULL,
     `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `fk_lens_family1_idx` (`family_id` ASC),
  CONSTRAINT `fk_lens_family1`
    FOREIGN KEY (`family_id`)
    REFERENCES `ecommerceidea`.`family` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ecommerceidea`.`driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerceidea`.`driver` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`driver` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `family_id` INT(11) NOT NULL,
  `dim` BINARY(4) NOT NULL,
  `brand` VARCHAR(20) NULL,
  `current` INT(10) NOT NULL,
  `voltage` INT(10) NOT NULL,
  `image` VARCHAR(255),
  `price` decimal(10,2) NOT NULL,
     `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `fk_driver_family1_idx` (`family_id` ASC),
  CONSTRAINT `fk_driver_family1`
    FOREIGN KEY (`family_id`)
    REFERENCES `ecommerceidea`.`family` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ecommerceidea`.`frame`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerceidea`.`frame` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`frame` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255),
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `price` decimal(10,2) NOT NULL,
  `family_id` INT(11) NOT NULL,
  `image2` VARCHAR(255),
     `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `fk_frame_family1_idx` (`family_id` ASC),
  CONSTRAINT `fk_frame_family1`
    FOREIGN KEY (`family_id`)
    REFERENCES `ecommerceidea`.`family` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ecommerceidea`.`LED`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerceidea`.`LED` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`LED` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `power` decimal NOT NULL,
  `size` VARCHAR(20),
  `color_t` INT(11) NOT NULL,
  `image` VARCHAR(255),
  `price` decimal NOT NULL,
  `family_id` INT(11) NOT NULL,
     `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `fk_LED_family1_idx` (`family_id` ASC),
  CONSTRAINT `fk_LED_family1`
    FOREIGN KEY (`family_id`)
    REFERENCES `ecommerceidea`.`family` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ecommerceidea`.`colors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerceidea`.`colors` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`colors` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `color` VARCHAR(7) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ecommerceidea`.`colors_has_family`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerceidea`.`colors_has_family` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`colors_has_family` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `colors_id` INT NOT NULL,
  `family_id` INT NOT NULL,
     `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `fk_colors_has_family_family1_idx` (`family_id` ASC),
  INDEX `fk_colors_has_family_colors1_idx` (`colors_id` ASC),
  CONSTRAINT `fk_colors_has_family_colors1`
    FOREIGN KEY (`colors_id`)
    REFERENCES `ecommerceidea`.`colors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_colors_has_family_family1`
    FOREIGN KEY (`family_id`)
    REFERENCES `ecommerceidea`.`family` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

USE `ecommerceidea` ;

-- -----------------------------------------------------
-- Table `ecommerceidea`.`orderdetails`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `ecommerceidea`.`item` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`item` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `led_id` INT(11) NOT NULL,
  `lens_id` INT(11) NOT NULL,
  `colors_id` INT(11) NOT NULL,
  `frame_id` INT(11) NOT NULL,
  `driver_id` INT(11) NOT NULL,  
  `price` decimal NOT NULL,
`image` VARCHAR(255),
  `code` VARCHAR(20) NULL DEFAULT NULL,
  `quantity` INT(4) NOT NULL DEFAULT 1,
     `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `fk_item_led1_idx` (`led_id` ASC),
  CONSTRAINT `fk_item_led1`
    FOREIGN KEY (`led_id`)
    REFERENCES `ecommerceidea`.`led` (`id`),
INDEX `fk_item_frame1_idx` (`frame_id` ASC),
CONSTRAINT `fk_item_frame1`
    FOREIGN KEY (`frame_id`)
    REFERENCES `ecommerceidea`.`frame` (`id`),
INDEX `fk_item_lens1_idx` (`lens_id` ASC),
CONSTRAINT `fk_item_lens1`
    FOREIGN KEY (`lens_id`)
    REFERENCES `ecommerceidea`.`lens` (`id`),
INDEX `fk_item_colors1_idx` (`colors_id` ASC),
CONSTRAINT `fk_item_colors1`
    FOREIGN KEY (`colors_id`)
    REFERENCES `ecommerceidea`.`colors` (`id`),
INDEX `fk_item_driver1_idx` (`driver_id` ASC),
CONSTRAINT `fk_item_driver1`
    FOREIGN KEY (`driver_id`)
    REFERENCES `ecommerceidea`.`driver` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `ecommerceidea`.`wishlist` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`wishlist` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `item_id` INT(11) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `fk_wishlist_item1_idx` (`item_id` ASC),
  CONSTRAINT `fk_wishlist_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `ecommerceidea`.`item` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS `ecommerceidea`.`orderitem` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `item_id` INT(11) NOT NULL,
  `order_id` INT(11) NOT NULL,
  `quantity` INT(11) NOT NULL DEFAULT 1,
  `price` decimal(10,2) NOT NULL,  
  `description` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `fk_orderitem_item1_idx` (`item_id` ASC),
  CONSTRAINT `fk_orderitem_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `ecommerceidea`.`item` (`id`),
INDEX `fk_orderitem_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_orderitem_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `ecommerceidea`.`order` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `ecommerceidea`.`order` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`order` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `total` decimal NOT NULL,
  `price` decimal NOT NULL,  
  `description` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `orderitem_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_orderitem1_idx` (`orderitem_id` ASC),
  CONSTRAINT `fk_order_orderitem1`
    FOREIGN KEY (`orderitem_id`)
    REFERENCES `ecommerceidea`.`orderitem` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;





DROP TABLE IF EXISTS `ecommerceidea`.`users` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(500) NULL DEFAULT NULL,
  `Password` VARCHAR(500) NULL DEFAULT NULL,
  `FirstName` VARCHAR(50) NULL DEFAULT NULL,
  `LastName` VARCHAR(50) NULL DEFAULT NULL,
  `City` VARCHAR(90) NULL DEFAULT NULL,
  `State` VARCHAR(20) NULL DEFAULT NULL,
  `Zip` VARCHAR(12) NULL DEFAULT NULL,
  `EmailVerified` TINYINT(1) NULL DEFAULT 0,
  `RegistrationDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `VerificationCode` VARCHAR(20) NULL DEFAULT NULL,
  `IP` VARCHAR(50) NULL DEFAULT NULL,
  `Phone` VARCHAR(20) NULL DEFAULT NULL,
  `Country` VARCHAR(20) NULL DEFAULT NULL,
  `Address` VARCHAR(100) NULL DEFAULT NULL,
  `Address2` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

INSERT INTO `led`(`power`,`color_t`,`price`,`family_id`) VALUES 

(7.00, 2700 , 20, 1),
(13,  2700, 30, 1),
(18,  2700, 40, 1),
(7, 3000, 20, 1),
(13, 3000, 30, 1),
(18, 3000, 40, 1),
(9, 2700, 20, 2),
(13, 2700, 30, 2),
(18, 2700, 40, 2),
(3.2, 2700, 20, 3),
(19, 2700, 30, 3),
(7, 2700, 40, 3);




INSERT INTO `frame`(`name`,`image`, `description`,`price`,`family_id`, `image2`) VALUES 

('Redondo', 'fedro_marcored1.jpg' ,'Marco redondo con aro basculante, para empotrables Fedro',10.5, 1, 'fedro_marcored2.jpg' ),
('Cuadrado', 'fedro_marcocuad1.jpg', 'Marco cuadrado con aro basculante, para empotrables Fedro',10.5, 1, 'fedro_marcocuad2.jpg'),
('Redondo recedido', 'fedro_redrec1.jpg','Marco redondo recedido con aro basculante, para empotrables Fedro',10.5, 1,  'fedro_redrec2.jpg'),
('Cuadrado recedido', 'fedro_cuadrec1.jpg','Marco cuadrado recedido con aro basculante, para empotrables Fedro',10.5, 1, 'fedro_cuadrec2.jpg'),
('Cuerpo cilindrico', 'Croll_cabcil1.jpg','Cuerpo cilindrico con aro antiglare para cabezales Croll',10.5, 2, 'Croll_cabcil2.jpg'),
('Frente circular', 'Uro_frentecirc1.jpg','Frente de vidrio sellado para proyectores Uro',10.5, 3, 'Uro_frentecirc2.jpg');


INSERT INTO `driver`(`family_id`,`dim`,`brand`,`current`,`voltage`,`price` ) VALUES 

(1,1,'Helvar', 350 , 220, 10.5 ),
(1,1,'TCI', 350 , 220, 10.5 ),
(2,1,'Phillips', 700 , 220, 10.5 ),
(3,1,'HEP', 700 , 220, 10.5 );


INSERT INTO `family`(`name`,`code`,`category` ) VALUES 

('Fedro','FED', 'empotrable'),
('Croll','CRL', 'cabezal'),
('Uro','URO', 'exterior');

INSERT INTO `colors`(`name`,`color`) VALUES 

('Blanco texturado','#FFFFFF'),
('Negro texturado','#000000'),
('Gris grafito','#46E51');