-- MySQL Script generated by MySQL Workbench
-- Fri Sep 20 15:54:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecommerceidea
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerceidea
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecommerceidea`;
CREATE SCHEMA IF NOT EXISTS `ecommerceidea` DEFAULT CHARACTER SET latin1 ;
USE `ecommerceidea` ;

-- -----------------------------------------------------
-- Table `ecommerceidea`.`families`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerceidea`.`families` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`families` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `code` VARCHAR(3) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ecommerceidea`.`lenses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerceidea`.`lenses` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`lenses` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `angle` INT(11) NOT NULL,
  `image` VARCHAR(255),
  `price` decimal(10,2) NOT NULL,
  `family_id` INT(11) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `lenses_family_id_foreign` (`family_id` ASC),
  CONSTRAINT `lenses_family_id_foreign`
    FOREIGN KEY (`family_id`)
    REFERENCES `ecommerceidea`.`families` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ecommerceidea`.`drivers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerceidea`.`drivers` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`drivers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `family_id` INT(11) NOT NULL,
  `dim` VARCHAR(255),
  `brand` VARCHAR(20) NULL,
  `current` INT(10) NOT NULL,
  `voltage` INT(10) NOT NULL,
  `image` VARCHAR(255),
  `price` DECIMAL(10,2) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `drivers_family_id_foreign` (`family_id` ASC),
  CONSTRAINT `drivers_family_id_foreign`
    FOREIGN KEY (`family_id`)
    REFERENCES `ecommerceidea`.`families` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ecommerceidea`.`frames`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerceidea`.`frames` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`frames` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255),
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `price` decimal(10,2) NOT NULL,
  `family_id` INT(11) NOT NULL,
  `image2` VARCHAR(255),
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `frames_family_id_foreign` (`family_id` ASC),
  CONSTRAINT `frames_family_id_foreign`
    FOREIGN KEY (`family_id`)
    REFERENCES `ecommerceidea`.`families` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ecommerceidea`.`leds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerceidea`.`leds` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`leds` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `power` DECIMAL NOT NULL,
  `size` VARCHAR(20),
  `color_t` INT(11) NOT NULL,
  `minflux` INT(11) NULL,
   `maxflux` INT(11) NULL,
  `image` VARCHAR(255),
  `price` decimal(10,2) NOT NULL,
  `family_id` INT(11) NOT NULL,
`description` VARCHAR(255) NULL DEFAULT NULL,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `leds_family_id_foreign` (`family_id` ASC),
  CONSTRAINT `leds_family_id_foreign`
    FOREIGN KEY (`family_id`)
    REFERENCES `ecommerceidea`.`families` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ecommerceidea`.`colors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerceidea`.`colors` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`colors` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `number` INT(3) NULL,
  `color_hex_code` VARCHAR(7) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ecommerceidea`.`color_frame`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerceidea`.`color_frame` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`color_frame` (
`id` INT(11) NOT NULL AUTO_INCREMENT,
  `color_id` INT NOT NULL,
  `frame_id` INT NOT NULL,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `color_frame_color_id` (`color_id` ASC),
  INDEX `color_frame_frame_id` (`frame_id` ASC),
  CONSTRAINT `color_frame_color_id`
    FOREIGN KEY (`color_id`)
    REFERENCES `ecommerceidea`.`colors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `color_frame_frame_id`
    FOREIGN KEY (`frame_id`)
    REFERENCES `ecommerceidea`.`frames` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

USE `ecommerceidea` ;


DROP TABLE IF EXISTS `ecommerceidea`.`wishlists` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`wishlists` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `user_id` INT(11) NOT NULL,
   INDEX `wishlists_user_id_foreign` (`user_id` ASC),
  CONSTRAINT `wishlists_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecommerceidea`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


DROP TABLE IF EXISTS `ecommerceidea`.`orders` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `totalprice` DECIMAL NOT NULL,  
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  `user_id` INT(11) NOT NULL,
   INDEX `orders_user_id_foreign` (`user_id` ASC),
  CONSTRAINT `orders_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecommerceidea`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


DROP TABLE IF EXISTS `ecommerceidea`.`users` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(500) NULL DEFAULT NULL,
  `Password` VARCHAR(500) NULL DEFAULT NULL,
  `FirstName` VARCHAR(50) NULL DEFAULT NULL,
  `LastName` VARCHAR(50) NULL DEFAULT NULL,
  `City` VARCHAR(90) NULL DEFAULT NULL,
  `State` VARCHAR(20) NULL DEFAULT NULL,
  `Zip` VARCHAR(12) NULL DEFAULT NULL,
  `EmailVerified` TINYINT(1) NULL DEFAULT 0,
  `RegistrationDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `VerificationCode` VARCHAR(20) NULL DEFAULT NULL,
  `IP` VARCHAR(50) NULL DEFAULT NULL,
  `Phone` VARCHAR(20) NULL DEFAULT NULL,
  `Country` VARCHAR(20) NULL DEFAULT NULL,
  `Address` VARCHAR(100) NULL DEFAULT NULL,
  `Address2` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


DROP TABLE IF EXISTS `ecommerceidea`.`item` ;

CREATE TABLE IF NOT EXISTS `ecommerceidea`.`item` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `led_id` INT(11) NOT NULL,
  `lens_id` INT(11) NOT NULL,
  `frame_id` INT(11) NOT NULL,
  `driver_id` INT(11) NOT NULL,  
  `order_id` INT(11) NOT NULL, 
 `wishlist_id` INT(11) NOT NULL, 
  `price` decimal NOT NULL,
  `image` VARCHAR(255),
  `code` VARCHAR(20) NULL DEFAULT NULL,
  `quantity` INT(4) NOT NULL DEFAULT 1,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  INDEX `items_led_id_foreign` (`led_id` ASC),
  CONSTRAINT `items_led_id_foreign`
    FOREIGN KEY (`led_id`)
    REFERENCES `ecommerceidea`.`leds` (`id`),
INDEX `items_frame_id_foreign` (`frame_id` ASC),
CONSTRAINT `items_frame_id_foreign`
    FOREIGN KEY (`frame_id`)
    REFERENCES `ecommerceidea`.`frames` (`id`),
INDEX `items_lens_id_foreign` (`lens_id` ASC),
CONSTRAINT `items_lens_id_foreign`
    FOREIGN KEY (`lens_id`)
    REFERENCES `ecommerceidea`.`lenses` (`id`),
INDEX `items_driver_id_foreign` (`driver_id` ASC),
CONSTRAINT `items_driver_id_foreign`
    FOREIGN KEY (`driver_id`)
    REFERENCES `ecommerceidea`.`drivers` (`id`),
INDEX `items_order_id_foreign` (`order_id` ASC),
CONSTRAINT `items_order_id_foreign`
    FOREIGN KEY (`order_id`)
    REFERENCES `ecommerceidea`.`orders` (`id`),
INDEX `items_wishlist_id_foreign` (`wishlist_id` ASC),
CONSTRAINT `items_wishlist_id_foreign`
    FOREIGN KEY (`wishlist_id`)
    REFERENCES `ecommerceidea`.`wishlists` (`id`),
      PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

INSERT INTO `leds`(`power`,`color_t`,`price`,`family_id`) VALUES 

(7.00, 2700 , 20, 1),
(13,  2700, 30, 1),
(18,  2700, 40, 1),
(7, 3000, 20, 1),
(13, 3000, 30, 1),
(18, 3000, 40, 1),
(9, 2700, 20, 2),
(13, 2700, 30, 2),
(18, 2700, 40, 2),
(3.2, 2700, 20, 3),
(19, 2700, 30, 3),
(7, 2700, 40, 3);




INSERT INTO `frames`(`name`,`image`, `description`,`price`,`family_id`, `image2`) VALUES 

('Redondo', 'fedro_marcored1.jpg' ,'Marco redondo con aro basculante, para empotrables Fedro',10.5, 1, 'fedro_marcored2.jpg' ),
('Cuadrado', 'fedro_marcocuad1.jpg', 'Marco cuadrado con aro basculante, para empotrables Fedro',10.5, 1, 'fedro_marcocuad2.jpg'),
('Redondo recedido', 'fedro_redrec1.jpg','Marco redondo recedido con aro basculante, para empotrables Fedro',10.5, 1,  'fedro_redrec2.jpg'),
('Cuadrado recedido', 'fedro_cuadrec1.jpg','Marco cuadrado recedido con aro basculante, para empotrables Fedro',10.5, 1, 'fedro_cuadrec2.jpg'),
('Cuerpo cilindrico', 'Croll_cabcil1.jpg','Cuerpo cilindrico con aro antiglare para cabezales Croll',10.5, 2, 'Croll_cabcil2.jpg'),
('Frente circular', 'Uro_frentecirc1.jpg','Frente de vidrio sellado para proyectores Uro',10.5, 3, 'Uro_frentecirc2.jpg');


INSERT INTO `drivers`(`family_id`,`dim`,`brand`,`current`,`voltage`,`price` ) VALUES 

(1,1,'Helvar', 350 , 220, 10.5 ),
(1,1,'TCI', 350 , 220, 10.5 ),
(2,1,'Phillips', 700 , 220, 10.5 ),
(3,1,'HEP', 700 , 220, 10.5 );


INSERT INTO `families`(`name`,`code`,`category` ) VALUES 

('Fedro','FED', 'empotrable'),
('Croll','CRL', 'cabezal'),
('Uro','URO', 'exterior');

INSERT INTO `colors`(`name`,`color_hex_code`) VALUES 

('Blanco texturado','#FFFFFF'),
('Negro texturado','#000000'),
('Gris grafito','#46E51');